---
---
<p>&nbsp;</p>
<p>&nbsp;</p>

<center>
<font size=36>
Ro Allen
</font>
</center>

<p>&nbsp;</p>

<blockquote>
  <h3>Research Statement</h3>
  <p style="text-align:justify">My goal is to advance our fundamental understanding of marine microbial ecology, leveraging rapidly developing molecular and statistical techniques to approach both hypothesis driven and exploratory studies. This understanding, ultimately, will contribute to our ability to predict, manipulate, and harness microbial communities, with far-reaching implications across a range of systems. </p>
</blockquote>

<p>&nbsp;</p>

#### Education & Employment    
***

<p style="text-align:center">
<b> The Marine Biological Association of the United Kingdom </b> [2019-Present]    
Postdoctoral Researcher   
Dr. Michael Cunliffe     
</p>
<p>&nbsp;</p>

<p style="text-align:center">
<b> University of Otago </b> [2016-2019]    
PhD Botany (Exceptional Thesis Award)   
"Marine microbial community dynamics and responses to oceanic climate change"    
Dr. Linn Hoffmann & Dr. Tina Summerfield     
</p>
<p>&nbsp;</p>
<p style="text-align:center">
<b> Plymouth University</b> [2014-2015]    
MRes Marine Biology (Distinction)    
"Effects of elevated CO<sub>2</sub> on invertebrate settlement communities: local and regional trends"   
Prof. Jason Hall-Spencer & Dr. Andy Foggo     
</p>
<p>&nbsp;</p>
<p style="text-align:center">
<b> Plymouth University</b> [2010-2013]    
BSc Hons. Marine Biology & Coastal Ecology (2:1)   
Prof. Jason Hall-Spencer  
</p>

<p>&nbsp;</p>

#### Publications   
***

<p style="text-align:justify">
[Allen, R., Hoffmann, L. J., Law, C. S., Summerfield, T. C. (2020)](https://sfamjournals.onlinelibrary.wiley.com/doi/epdf/10.1111/1758-2229.12844). Subtle bacterioplankton community responses to elevated CO<sub>2</sub> and warming in the oligotrophic South Pacific Gyre. *Environmental Microbiology Reports*, Early View. 
</p>

<p style="text-align:justify">
[Allen, R., Foggo, A., Fabricius, K., Balistreri, A., & Hall-Spencer, J. M. (2017)](http://www.sciencedirect.com/science/article/pii/S0025326X1631013X). Tropical CO<sub>2</sub> seeps reveal the impact of ocean acidification on coral reef invertebrate recruitment. *Marine Pollution Bulletin*, 124, 2, 607-613.
</p>

<p style="text-align:justify">
[Hall-Spencer, J. M., & Allen, R. (2015)](https://www.dovepress.com/the-impact-of-co2-emissions-on-39nuisance39-marine-species-peer-reviewed-article-RRBS). The impact of CO<sub>2</sub> emissions on “nuisance” marine species. *Research and Reports in Biodiversity Studies*, 4, 33-46.
</p>

<p>&nbsp;</p>

#### Conference Papers   
***

<p style="text-align:justify">
[Allen, R., Summerfield, T., Harvey, B., Agostini, S., Hoffmann, L. (2019)](http://nzoac.nz/workshops/). Biofilm succession in an acidified ocean: mechanistic insights from a volcanic CO<sub>2</sub> seep study. *12th New Zealand Ocean Acidification Workshop*. [Talk]
</p>

<p style="text-align:justify">
[Allen, R., Hoffmann, L., Law, C., Louisson, Z., Summerfield, T. (2018)](17.isme-microbes.org). Microbial community assembly processes in the oligotrophic South Pacific Gyre. *17th International Symposium on Microbial Ecology*. [Poster]
</p>

<p style="text-align:justify">
[Summerfield, T., Louisson, Z., Nilsen, A., Allen, R., Orlovich, D. (2018)](17.isme-microbes.org). Investigating canopy soil microhabitats. *17th International Symposium on Microbial Ecology*. [Poster]
</p>

<p style="text-align:justify">
[Allen, R., Summerfield, T., Harvey, B., Agostini, S., Wada, S., Rudminat, F., Hoffmann, L. (2018)](http://www.otago.ac.nz/oerc/news/index.html#events). Volcanic CO<sub>2</sub> Seeps provide insights into benthic diatom proliferation in a high CO<sub>2</sub> ocean. *3rd New Zealand Symposium on Algae and Photosynthetic Prokaryotes*. [Talk]
</p>

<p style="text-align:justify">
[Allen, R., Hoffmann, L., Law, C., Rudminat, F., Summerfield, T. (2018)](http://nzoac.nz/workshops/). Bacterioplankton resistance to acidification and warming in the oligotrophic ocean. *11th New Zealand Ocean Acidification Workshop*. [Talk]
</p>

<p style="text-align:justify">
[Allen, R., Hoffmann, L., Law, C., Rudminat, F., Summerfield, T. (2017)](http://www.nzmolecol.org/conferences). South Pacific gyre bacterioplankton responses to oceanic climate change. *New Zealand Molecular Ecology Conference*. [Talk]
</p>

<p style="text-align:justify">
[Gutierrez-Rodriguez, A., Safi, K., Gall, M., MacAskill, S., Allen, R., Rudminat, F., Hoffmann, L., Nodder, S. (2017)](https://www.uts.edu.au/research-and-teaching/our-research/climate-change-cluster/events/c3-2017-colloquium-aquafluo-ii). Phytoplankton photophysiology and productivity across contrasting subtropical and subantarctic waters of the South West Pacific. *Climate Change Cluster Colloquium – AquaFluo II*. [Talk]
</p>

<p style="text-align:justify">
[Allen, R., Summerfield, T., Law, C.,  Hoffmann, L. (2017)](http://nzoac.nz/workshops/). The ecological and evolutionary importance of genetic diversity in phytoplankton responses to ocean acidification
*10th New Zealand Ocean Acidification Workshop*. [Talk]
</p>

<p style="text-align:justify">
[Allen, R., Foggo, A., Fabricius, K., Balistreri, A., Hall-Spencer, J. (2016)](http://nzoac.nz/workshops/). The effect of ocean acidification on coral reef invertebrate recruitment at CO<sub>2</sub> seeps in Papua New Guinea. *9th New Zealand Ocean Acidification Workshop*. [Talk]
</p>

<p style="text-align:justify">
[Allen, R., Foggo, A., Fabricius, K., Balistreri, A., Hall-Spencer, J. (2016)](http://www.biosch.hku.hk/icmpe8/). Elevated CO<sub>2</sub> disrupts invertebrate colonization on tropical coral reefs. *8th International Conference on Marine Pollution and Ecotoxicology*. [Poster]
</p>

<p style="text-align:justify">
[Allen, R., Foggo, A., Fabricius, K., Balistreri, A., Hall-Spencer, J. (2015)](https://www.qub.ac.uk/sites/12thmba/). The impact of ocean acidification on invertebrate settlement at CO<sub>2</sub> seeps. *12th Marine Biological Association Postgraduate Conference*. [Poster]
</p>

<p>&nbsp;</p>

#### Key Skills   
***

<style>
.column-left{
  float: left;
  width: 33%;
  text-align: left;
}
.column-center{
  display: inline-block;
  width: 33%;
  text-align: center;
}
.column-right{
  float: right;
  width: 33%;
  text-align: right;
}
</style>

<div class="column-left">
<center>
[<i class="fa fa-flask" style="font-size:30px"></i>]()     
<br>Amplicon sequencing</br>
<br>PCR & qPCR</br>
<br>Primer design</br>
<br>DNA extraction</br> 
<center>
</div>
<div class="column-center">
<center>
[<i class="fa fa-line-chart" style="font-size:30px"></i>]()     
<br>Mulitvariate statistics</br>
<br>Compositional statistics</br>
<br>Bioinformatics</br>
<br>R</br>
</center>
</div>
<div class="column-right">
<center>
[<i class="fa fa-tint" style="font-size:30px"></i>]()     
<br>Cell culture</br>
<br>Flow cytometry</br>
<br>Scanning electron microscopy</br>
<br>Fast repetition rate fluorometry</br>
</center>
</div>

<p>&nbsp;</p>

#### Grants   
***

<p style="text-align:justify">
<b> Doctoral Scholarship </b> (~$100,000)  
    University of Otago [2016-Present]  
</p>

<p style="text-align:justify">
<b> Seed Funding Grant </b> ($4852)  
    University of Otago Polar Environments Research Theme [2017]  
</p>

<p style="text-align:justify">
<b> Seed Funding Grant </b> ($2500)  
    University of Otago Ocean Acidification Research Theme [2016]  
</p>

<p style="text-align:justify">
<b> International Travel Grant </b> ($2000)  
    University of Otago Division of Sciences [2017]  
</p>

<p style="text-align:justify">
<b> Student Travel Grant </b> ($400)  
    New Zealand Ocean Acidification Community [2018]  
</p>

<p style="text-align:justify">
<b> Student Travel Grant </b> ($300)  
    New Zealand Ocean Acidification Community [2016]  
</p>

<p style="text-align:justify">
<b> Student Travel Grant </b> (£200)  
    Plymouth University [2015]  
</p>

<p>&nbsp;</p>

#### Awards   
***

<p style="text-align:justify">
<b> Best Talk Award </b>   
    University of Otago Department of Botany Colloquium [2017]  
</p>

<p style="text-align:justify">
<b> Best Talk Award </b>   
    10th New Zealand Ocean Acidification Workshop [2016]  
</p>

<p>&nbsp;</p>

#### Teaching   
***

<p style="text-align:justify">
<b> Guest Lecturer: </b> [Molecular and Cellular Approaches in Marine Biology](https://www.plymouth.ac.uk/courses/postgraduate/mres-marine-biology)        
    The Marine Biological Association [2019-Present]  
</p>

<p style="text-align:justify">
<b> Guest Lecturer: </b> [Marine Ecology and Conservation](https://www.plymouth.ac.uk/courses/postgraduate/mres-marine-biology)        
    The Marine Biological Association [2019-Present]  
</p>

<p style="text-align:justify">
<b> Guest Lecturer: </b> [Aquatic Microbial Ecology](https://www.plymouth.ac.uk/courses/postgraduate/mres-marine-biology)        
    Plymouth University [2019-Present]  
</p>

<p style="text-align:justify">
<b> Guest Lecturer: </b> [Plants: How They Shape the World](http://www.otago.ac.nz/botany/study/papers/biol123.html)        
    University of Otago [2018]  
</p>

<p style="text-align:justify">
<b> Guest Lecturer: </b> [Marine and Freshwater Botany](http://www.otago.ac.nz/botany/study/papers/btny203.html)        
    University of Otago [2017]  
</p>

<p style="text-align:justify">
<b> Senior Demonstrator: </b> [Plants: How They Shape the World](http://www.otago.ac.nz/botany/study/papers/biol123.html)  
    University of Otago [2017-Present]  
</p>

<p style="text-align:justify">
<b> Demonstrator: </b> [Cell and Molecular Biology](http://www.otago.ac.nz/courses/papers/?papercode=CELS191#2018)  
    University of Otago [2016-Present]  
</p>

<p style="text-align:justify">
<b> Demonstrator: </b> [Applied Plant Science](http://www.otago.ac.nz/courses/papers/index.html?papercode=PLBI301#2018)  
    University of Otago [2016-Present]  
</p>

<p style="text-align:justify">
<b> Demonstrator: </b> [Marine and Freshwater Botany](http://www.otago.ac.nz/botany/study/papers/btny203.html)  
    University of Otago [2016-Present]  
</p>

<p>&nbsp;</p>

#### Outreach   
***

<p style="text-align:justify">
<b> Speaker: </b> [Ōku Moana: International Science Week](http://www.scifest.org.nz/events/meet-a-scientist-the-air-we-breathe)   
    University of Otago Department of Botany [2018]  
</p>

<p style="text-align:justify">
<b> Representative: </b> [International Science Week](http://www.scifest.org.nz)   
    University of Otago Department of Botany [2018]  
</p>

<p style="text-align:justify">
<b> Programme Coordinator: </b> [Hands-On at Otago](http://www.otago.ac.nz/hands-on-at-otago/index.html)   
    University of Otago Department of Botany [2018]  
</p>

<p style="text-align:justify">
<b> Scientist and Collaborator: </b> [Art + Oceans](http://sustainableseaschallenge.co.nz/news-updates/art-oceans-2018)   
    University of Otago & Dunedin School of Art [2017-2018]  
</p>

<p style="text-align:justify">
<b> Interviewee: </b> [8 Billion Angels Documentary](https://8billionangels.org)   
    8 Billion Angels Productions LLC [2017]  
</p>

<p style="text-align:justify">
<b> Representative: </b> [Tertiary Open Day](http://www.otago.ac.nz/about/open_day_pgm.html)   
    University of Otago Department of Botany [2017]  
</p>

<p style="text-align:justify">
<b> Coordinator: </b> [Department Colloquium](http://www.otago.ac.nz/botany/index.html)   
    University of Otago Department of Botany [2017]  
</p>

<p>&nbsp;</p>

#### Qualifications   
***

<p style="text-align:justify">
HSE Part IV Professional Air Diver  
</p>

<p style="text-align:justify">
PADI Open Water Scuba Instructor (#260394)
</p>

<p style="text-align:justify">
RYA Powerboat Level 2 License 
</p>

<p style="text-align:justify">
VHF Radio Qualified
</p>

<p style="text-align:justify">
HSE Certificate of Competence: Automatic External Defibrillation 
</p>

<p style="text-align:justify">
HSE Certificate of Competence: Oxygen Administration
</p>

<p style="text-align:justify">
HSE Certificate of Competence: Manual Handling Techniques
</p>

<p style="text-align:justify">
MCA Certificate of Competence: Personal Survival Techniques 
</p>

<p style="text-align:justify">
MCA Certificate of Competence: Personal Safety & Social Responsibility
</p>

<p style="text-align:justify">
Institution of Fire Engineers: Basic Fire Awareness Training
</p>

<p>&nbsp;</p>

#### Professional Development   
***

<p style="text-align:justify">
RNA-Seq: What is state of the art? Bioinformatics Workshop
</p>

<p style="text-align:justify">
Research Bazaar Otago – Statistics and Data Manipulation
</p>

<p style="text-align:justify">
Software Carpentry for ‘R’
</p>

<p style="text-align:justify">
Data Visualization with 'ggplot2' Workshop
</p>

<p style="text-align:justify">
University of Otago Demonstrating/Tutoring Workshop
</p>

<p>&nbsp;</p>

#### Memberships   

***

<p style="text-align:justify">
New Zealand Ocean Acidification Community: [Council Member 2016-2019](http://nzoac.nz)
</p>

<p style="text-align:justify">
[Microbiology Society](https://microbiologysociety.org)
</p>


<p style="text-align:justify">
[International Society for Microbial Ecology](https://www.isme-microbes.org)
</p>

<p style="text-align:justify">
[Genetics Otago](www.otago.ac.nz/genetics/index.html) 
</p>

<p style="text-align:justify">
[Marine Biological Association](www.mba.ac.uk)
</p>

<p style="text-align:justify">
[British Ecological Society](britishecologicalsociety.org)
</p>

<p style="text-align:justify">
[New Zealand Marine Sciences Society](nzmss.org)
</p>

<p>&nbsp;</p>

#### Extra-Curricular    
***

<p style="text-align:justify">
University of Otago Rugby League First XIII [2016-Present]
</p>

<p style="text-align:justify">
University of Otago Rugby League Executive Committee [2016-2018]
</p>

<p style="text-align:justify">
New Zealand Universities Invitational Rugby League Tournament [2017]
</p>

<p style="text-align:justify">
Cherwell School First XV Rugby Union Captain [2008-2009]
</p>

<p style="text-align:justify">
Muay-Thai TFC English Title Challenger [2012]
</p>

<p style="text-align:justify">
Muay-Thai Coach [2010-2013]
</p>