---
title: "Publications"
---
<p>&nbsp;</p>

#### Journal Articles    
***

<p style="text-align:justify">
[Allen, R., Hoffmann, L. J., Larcombe, M. J., Louisson, Z., Summerfield, T. C. (In Review)](). Selection dominates microbial community assembly in the oligotrophic South Pacific Gyre 
</p>

<p style="text-align:justify">
[Allen, R., Hoffmann, L. J., Law, C. S., Summerfield, T. C. (2020)](https://sfamjournals.onlinelibrary.wiley.com/doi/epdf/10.1111/1758-2229.12844). Subtle bacterioplankton community responses to elevated CO<sub>2</sub> and warming in the oligotrophic South Pacific Gyre. *Environmental Microbiology Reports*, Early View. 
</p>

<p style="text-align:justify">
[Allen, R., Foggo, A., Fabricius, K., Balistreri, A., & Hall-Spencer, J. M. (2017)](http://www.sciencedirect.com/science/article/pii/S0025326X1631013X). Tropical CO<sub>2</sub> seeps reveal the impact of ocean acidification on coral reef invertebrate recruitment. *Marine Pollution Bulletin*, 124, 2, 607-613.
</p>

<p style="text-align:justify">
[Hall-Spencer, J. M., & Allen, R. (2015)](https://www.dovepress.com/the-impact-of-co2-emissions-on-39nuisance39-marine-species-peer-reviewed-article-RRBS). The impact of CO<sub>2</sub> emissions on “nuisance” marine species. *Research and Reports in Biodiversity Studies*, 4, 33-46.
</p>


<p>&nbsp;</p>

#### Conference Papers   
***
<p style="text-align:justify">
[Allen, R., Hoffmann, L., Law, C., Louisson, Z., Summerfield, T. (2018)](17.isme-microbes.org). Microbial community assembly processes in the oligotrophic South Pacific Gyre. *17th International Symposium on Microbial Ecology*. [Poster]
</p>

<p style="text-align:justify">
[Summerfield, T., Louisson, Z., Nilsen, A., Allen, R., Orlovich, D. (2018)](17.isme-microbes.org). Investigating canopy soil microhabitats. *17th International Symposium on Microbial Ecology*. [Poster]
</p>

<p style="text-align:justify">
[Allen, R., Summerfield, T., Harvey, B., Agostini, S., Wada, S., Rudminat, F., Hoffmann, L. (2018)](http://www.otago.ac.nz/oerc/news/index.html#events). Volcanic CO<sub>2</sub> Seeps provide insights into benthic diatom proliferation in a high CO<sub>2</sub> ocean. *3rd New Zealand Symposium on Algae and Photosynthetic Prokaryotes*. [Talk]
</p>

<p style="text-align:justify">
[Allen, R., Hoffmann, L., Law, C., Rudminat, F., Summerfield, T. (2018)](http://nzoac.nz/workshops/). Bacterioplankton resistance to acidification and warming in the oligotrophic ocean. *11th New Zealand Ocean Acidification Workshop*. [Talk]
</p>

<p style="text-align:justify">
[Allen, R., Hoffmann, L., Law, C., Rudminat, F., Summerfield, T. (2017)](http://www.nzmolecol.org/conferences). South Pacific gyre bacterioplankton responses to oceanic climate change. *New Zealand Molecular Ecology Conference*. [Talk]
</p>

<p style="text-align:justify">
[Gutierrez-Rodriguez, A., Safi, K., Gall, M., MacAskill, S., Allen, R., Rudminat, F., Hoffmann, L., Nodder, S. (2017)](https://www.uts.edu.au/research-and-teaching/our-research/climate-change-cluster/events/c3-2017-colloquium-aquafluo-ii). Phytoplankton photophysiology and productivity across contrasting subtropical and subantarctic waters of the South West Pacific. *Climate Change Cluster Colloquium – AquaFluo II*. [Talk]
</p>

<p style="text-align:justify">
[Allen, R., Summerfield, T., Law, C.,  Hoffmann, L. (2017)](http://nzoac.nz/workshops/). The ecological and evolutionary importance of genetic diversity in phytoplankton responses to ocean acidification
*10th New Zealand Ocean Acidification Workshop*. [Talk]
</p>

<p style="text-align:justify">
[Allen, R., Foggo, A., Fabricius, K., Balistreri, A., Hall-Spencer, J. (2016)](http://nzoac.nz/workshops/). The effect of ocean acidification on coral reef invertebrate recruitment at CO<sub>2</sub> seeps in Papua New Guinea. *9th New Zealand Ocean Acidification Workshop*. [Talk]
</p>

<p style="text-align:justify">
[Allen, R., Foggo, A., Fabricius, K., Balistreri, A., Hall-Spencer, J. (2016)](http://www.biosch.hku.hk/icmpe8/). Elevated CO<sub>2</sub> disrupts invertebrate colonization on tropical coral reefs. *8th International Conference on Marine Pollution and Ecotoxicology*. [Poster]
</p>

<p style="text-align:justify">
[Allen, R., Foggo, A., Fabricius, K., Balistreri, A., Hall-Spencer, J. (2015)](https://www.qub.ac.uk/sites/12thmba/). The impact of ocean acidification on invertebrate settlement at CO<sub>2</sub> seeps. *12th Marine Biological Association Postgraduate Conference*. [Poster]
</p>

<p>&nbsp;</p>

###Media
***

CBS News [Ocean acidification benefits invasive species](https://www.cbsnews.com/news/ocean-acidification-benefits-invasive-species/)

ScienceDaily [Marine invasive species benefiting from rising carbon dioxide levels](https://www.sciencedaily.com/releases/2015/11/151106113732.htm)

Oceanbites [Are marine “nuisance” species expected to increase under ocean acidification?](https://oceanbites.org/nuisance-species-increase-under-ocean-acidification/)

The Conversation [Attack of the jellies: the winners of ocean acidification](http://theconversation.com/attack-of-the-jellies-the-winners-of-ocean-acidification-50576)

X-Ray Magazine [Ocean acidification may well be helping invasive species](http://www.xray-mag.com/content/ocean-acidification-may-well-be-helping-invasive-species)

<p>&nbsp;</p>
<center>
<iframe width="560" height="315" src="https://www.youtube.com/embed/xvlHH0y2hwE" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>
</center>